### PR TITLE
Update dfdutils-included vulkan_core.h.

### PR DESCRIPTION
**Pull request by MarkCallow**
ASTC HDR and A4B4G4R4_UNORM formats are now core. Update all code to use the non _EXT names.

Add instructions and a script for regnerating vulkan_core.h.

### CODE REVIEW

**Comment by MarkCallow** [comment]
@aqnuep here is the updated Vulkan header. Some of the new tools tests are failing. I can't do any more tonight so I have pushed the branch and made a PR. I wanted to make this a work-in-progress PR but can't find the relevant control.

The test failures are most likely due to output strings. The ASTC HDR extension has become part of Vulkan core so there are now enums without the trailing _EXT in the name. This PR changes all the code to use the undecorated enums. I did not re-build the CTS tests as I have no time left.

Hope this helps.

**Comment by MarkCallow** [comment]
The test failures I've looked at so far have the form

```
331/626 Testing: ktxToolTests.info.invalid_file
331/626 Test: ktxToolTests.info.invalid_file
Command: "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9" "clitest.py" "tests/info/invalid_file.json" "--executable-path" "/Users/mark/Projects/khronos/github/KTX-Software/build/macos/Release/ktx" "--ktxdiff-path" "/Users/mark/Projects/khronos/github/KTX-Software/build/macos/Release/ktxdiff"
Directory: /Users/mark/Projects/khronos/github/KTX-Software/tests/cts/clitests
"ktxToolTests.info.invalid_file" start time: Oct 14 14:25 JST
Output:
----------------------------------------------------------
Executing test case 'tests/info/invalid_file.json'...
Traceback (most recent call last):
  File "/Users/mark/Projects/khronos/github/KTX-Software/tests/cts/clitests/clitest.py", line 286, in <module>
    output_file = open(output_filename, 'w', newline='\n', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'output/info/invalid_file.json.65.out'
<end of output>
Test time =   0.29 sec
----------------------------------------------------------
Test Failed.
"ktxToolTests.info.invalid_file" end time: Oct 14 14:25 JST
"ktxToolTests.info.invalid_file" time elapsed: 00:00:00

```

I don't see any output from the command being run (presumably ktx info in this case) so I'm not sure how to debug further. Please advise @aqnuep.

**Comment by MarkCallow** [comment]
I've fixed all the tests. The open question is should the --format option to create accept "_EXT" and core names? In this PR only the new names are accepted.

**Comment by aqnuep** [comment]
The core changes look good, but I see a lot of seemingly unrelated changes. Is that all just cleanup, or should I take a deeper look into those too?

**Comment by aqnuep** [comment]
Yes, I was referring to those changes. If all of those changes are intentional then it's all good.

**Review by aqnuep — APPROVED** [review]
LGTM

**Pull request merged**
