### PR TITLE
CMake configuration

### LINKED ISSUE #44: Replace GYP with CMake
I'm currently using libktx a sample app and want to integrate libktx into it. My project uses one cmake script for all platforms/configurations. I've started refactoring it pretty heavily @ https://github.com/bradc6/KTX/tree/refactor/cmake  (or more specifically https://github.com/bradc6/KTX/blob/refactor/cmake/build/cmake/linux/Debug/CMakeLists.txt)

I'm opening this issue to see if there is any interest in completing this 100% and making a pull request.

Thanks,
-Brad

### PR DESCRIPTION
**Pull request by atteneder**
I created a CMake configuration.

Purpose: Make it easy to integrate KTX loading/transcoding in 3rd party projects (especially CMake based ones)

It's a starting point to fix #44 

## Status

- [x] build ktx library
- [x] CTest testing
  - [x] unittests
  - [x] texturetests
- [x] tools
  - [x] ktx2check
  - [x] ktx2ktx2
  - [x] ktxinfo
  - [x] ktxsc
  - [x] toktx
- [x] Load test apps
  - [x] glloadtest
  - [ ] vkloadtest
    - [x] build
    - [ ] spir-v shader creation

## Tested on platforms 
- [x] macOS
- [ ] iOS
- [ ] Android
- [ ] WebGL
- [ ] Linux
- [ ] Windows

### CODE REVIEW

**Comment by MarkCallow** [comment]
I have had to merge PR #125 to get builds working again on my main development machine after I updated to Xcode11. Please rebase your work on HEAD ktx2 after this PR. The changes are likely to affect your work because they impact building vkloadtests, as the libvulkan.lazy target has been removed plus Mac specific changes to how libassimp is linked to vkloadtests.

**Comment by atteneder** [comment]
Alright, I'll have a look

**Comment by atteneder** [comment]
Alright, I rebased and added the missing executable targets.
As far as i can see what's still missing is the loadertests (GL and vulkan) and some (perl) scripts that auto-generate code/inc files.

**Comment by MarkCallow** [comment]
I've made more changes to the way the build is done. I felt it better to get all pending changes affecting the build done as quickly as possible so the new cmake build can incorporate them. The latest are:

1. Pr #126. This changes the libktx and ktxtools projects to use the same dstroot, e.g `/tmp/ktx.dst`, instead of different dstroots. It also fixes a problem in the `Packages` project for building the mac package. This does not affect cmake which starts the package build in the same way as before.

2. PR #127. This should not affect your cmake work at all. It removes the pre-generated VS2013 projects and adds VS2019 projects.

And to summarize PR #125:

- on the Mac: vkloadtests is now linked with a static libassimp from the `other_lib` folder instead of using a MacPorts or Brew installed library.
- libvulkan.lazy target was removed which, on Mac, means the -lazy_library `ld` options is gone.

I do not expect any further changes to the way the build is done.

**Comment by atteneder** [comment]
progress I made today:
glloadtests works again (on macOS)
vkloadtests is now building on macOS again. Running fails, I assume due to SPIR-V compilation not happening. I'll look into that later.

**Comment by atteneder** [comment]
I'm going to restructure my CMake configuration and try to make a cleaned-up PR soon.
If someone's interested, find my work in my fork in the mean-time.

**Pull request closed without merging**
