### PR TITLE
Universal Windows Platform support

### PR DESCRIPTION
**Pull request by atteneder**
Had to make OpenGL upload functions optional to get `libktx` to build for UWP.

### CODE REVIEW

**Comment by MarkCallow** [comment]
Is this actually necessary? glloader.c doesn't attempt to do anything unless the application calls the function and all it needs for building are the header files included in `other_include`. If the platform doesn't support OpenGL then the app won't be able to create a GL context which is a prerequisite to calling the ktxTexture[12]_GLUpload. Of course it will save a little space if it's not there and will avoid confusion.

**Comment by atteneder** [comment]
Can't remember exactly, but when creating this fix initially (against beta 6 iirc) I think it was necessary. Let me check.

Since we're at it: are there plans to implement similar upload functionality for further graphic APIs (Metal, Direct3D)?

**Comment by atteneder** [comment]
Sorry, I should've tested more thoroughly before submitting the PR.

I tried to configure/build but got lots of errors liket [this one](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4703?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4703)%26rd%3Dtrue&view=msvc-160). Looks like the default compiler configuration for this platform is more strict. You mentioned you're working on level 4 warning stuff, so I'll wait until that landed before I continue.

In case you want to try out UWP/ARM64, here's how I configured it:

`cmake . -G "Visual Studio 16 2019" -A ARM64 -B build_uwp_arm64 -DCMAKE_SYSTEM_NAME:String=WindowsStore -DCMAKE_SYSTEM_VERSION:String="10.0" -DBASISU_SUPPORT_SSE=OFF`

Thanks

**Comment by MarkCallow** [comment]
> Since we're at it: are there plans to implement similar upload functionality for further graphic APIs (Metal, Direct3D)?

I have no plan but I'd happily accept contributions.

> Sorry, I should've tested more thoroughly before submitting the PR.

It's building now without warnings. What did you do?

**Comment by MarkCallow** [comment]
I've landed PR #418 raising the warning level and fixing all the warnings. Please rebase your PRs.

**Comment by atteneder** [comment]
I added build instructions and fixed the cpu detection when cross compiling to UWP ARM/ARM64 (so that SSE is not mistakenly enabled)

**Comment by MarkCallow** [comment]
Please fix the conflicts. They're probably because I just landed the Android build PR.

**Pull request merged**
