### PR TITLE
Prevent warning if VK_NO_PROTOTYPES is already defined

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by MarkCallow** [comment]
@jherico how come you encountered this?  `vk_funcs.h` is internal to the library.

**Comment by jherico** [comment]
The [Vulkan-Sample](https://github.com/KhronosGroup/Vulkan-Samples/) uses KTX as a git submodule and incorporates the build directly into it's top level project, so any upstream warnings show up as part of the build of that project.

**Comment by MarkCallow** [comment]
> The [Vulkan-Sample](https://github.com/KhronosGroup/Vulkan-Samples/) uses KTX as a git submodule and incorporates the build directly into it's top level project, so any upstream warnings show up as part of the build of that project.

But where did the other definition of VK_NO_PROTOTYPES come from that was visible when libktx was being compiled? When you say "build directly" do you mean Vukan-Sample is including the libktx sources directly and setting up its own compile commands?

**Comment by jherico** [comment]
Yes, exactly.  https://github.com/KhronosGroup/Vulkan-Samples/blob/main/third_party/CMakeLists.txt#L50

**Comment by MarkCallow** [comment]
Thanks for the info. and this fix.

**Pull request merged**
