### PR TITLE
Add KTX_TESTS as cmake option.

### PR DESCRIPTION
**Pull request by ErixenCruz**
Closes https://github.com/KhronosGroup/KTX-Software/issues/330.

### CODE REVIEW

**Review by atteneder — APPROVED** [review]

**Comment by MarkCallow** [comment]
Will things work if `KTX_FEATURE_LOADTEST_APPS` is ON and `KTX_TESTS` is OFF? Why is it `KTX_TESTS` not `KTX_FEATURE_TESTS`?

**Comment by atteneder** [comment]
> Will things work if `KTX_FEATURE_LOADTEST_APPS` is ON and `KTX_TESTS` is OFF?

Neither the apps, gtests nor CLI tests would be included in that case. Would you want to turn of just the gtest apps in that case? I presumed the average user would want to disable all tests.

> Why is it `KTX_TESTS` not `KTX_FEATURE_TESTS`?

Could be changed, arguably.

**Comment by ErixenCruz** [comment]
Should I change the name `KTX_TESTS` to `KTX_FEATURE_TESTS`? @MarkCallow @atteneder

**Comment by atteneder** [comment]
> Should I change the name `KTX_TESTS` to `KTX_FEATURE_TESTS`? @MarkCallow @atteneder

Yes. It's more consistent and I guess Mark's question implies that he'd prefer that, right?

**Comment by MarkCallow** [comment]
> I guess Mark's question implies that he'd prefer that, right?

Correct.

>>    Will things work if KTX_FEATURE_LOADTEST_APPS is ON and KTX_TESTS is OFF?
>
>Neither the apps, gtests nor CLI tests would be included in that case. Would you want to turn of just the gtest apps in that case? I presumed the average user would want to disable all tests.

Making KTX_FEATURE_LOADTEST_APPS and KTX_FEATURE_TESTS independent looks to be simpler than implementing an error or warning when KTX_FEATURE_LOADTEST_APPS is ON and KTX_FEATURE_TESTS OFF or preventing that situation happening. So @ErixenCruz please make them independent. Move the IF KTX_FEATURE_TESTS into tests/CMakeLists.txt.

**Comment by ErixenCruz** [comment]
Ok I think its ready now.

**Comment by MarkCallow** [comment]
Thank you for this.

**Pull request merged**
