### PR TITLE
Minor reformat

### PR DESCRIPTION
**Pull request by lexaknyazev**
Follow-up to #398.

### CODE REVIEW

**Comment by joe198** [comment]
ok

**Comment by joe198** [comment]
#399

**Comment by MarkCallow** [comment]
Thanks. I hadn't realized the file still had tabs in it. All my editors are set up to use spaces instead of tabs.

**Comment by lexaknyazev** [comment]
@MarkCallow 
Should we reformat all sources with spaces?

**Comment by MarkCallow** [comment]
Yes I want to do that. Simply haven't had the time due to more pressing needs.

**Pull request merged**
