### PR TITLE
Fix incorrect index calculations in image conversions in ktx create

### PR DESCRIPTION
**Pull request by VaderY**
Fix incorrect index calculations in image conversions in ktx create (#733, #736)

### CODE REVIEW

**Review by MarkCallow — APPROVED** [review]

**Comment by MarkCallow** [comment]
@aqnuep please review.

**Comment by MarkCallow** [comment]
Why did the user not receive any notice of the crash?

And, less importantly, why did it produce an output file on macOS?

**Comment by aqnuep** [comment]
We discussed this change with @VaderY. It was a trivial oversight where row stride was incorrectly derived from the height instead of the width.

I'm not sure about the different behaviors across platforms, but I'd expect this typo would mainly only cause data corruption for non-square textures due to the incorrect row stride.

**Review by aqnuep — APPROVED** [review]
LGTM.

**Comment by aqnuep** [comment]
FYI, @MarkCallow, @VaderY also added a bunch of odd sized textures to the CTS to have better coverage on this front.

We apologize for the typo, but it's been a huge set of functionalities to cover with implementation and tests, and obviously this slipped through the cracks.

**Comment by VaderY** [comment]
> Why did the user not receive any notice of the crash?

Technically the exit code was an indicator (it was 0xC0000005 = Access Violation). But as it was a bug and not an error that we should ever handle, there was no reasonable way to produce an error message about it.
There are ways with C++ to intercept such crashes (breakpad, crashbed, signals, etc) and attempt to collect more information, write out coredumps and notify the user. But it is not a trivial undertaking to implement or adopt these in a cross platform manner.
 
> And, less importantly, why did it produce an output file on macOS?

Given some bad luck these kind of undefined behaviors are sometimes hidden on certain platform. When I checked in windows builds every compiler yielded a proper crash. Its possible that the application owned the memory pages that was written to and there was nothing important.

**Pull request merged**
