### PR TITLE
Adopt fmt 9.1.0 for formatting

### PR DESCRIPTION
**Pull request by VaderY**
As we discussed I am creating a separate PR just for adopting FMT (with git subrepo) directly againts the master branch,
so both ktx-tools and imageio could utilize fmt without having to depend on each other.

Currently -with this PR only- no target would use the library, but these commits would serve as a common branching points for targets that would wish to do so.

I have chosen the latest stable release: 9.1.0.

License:
[MIT license](https://github.com/fmtlib/fmt/blob/master/LICENSE.rst)

Documentation:
https://fmt.dev

For more info and for the source: 
https://github.com/fmtlib/fmt

To use and link fmt to a target:
```
target_link_libraries(<target> fmt::fmt)
```

Includes are the usual
```
#include <fmt/printf.h>
```

Usage is the usual as well
```
fmt::print("Hello, {}", "fmt");
```

### CODE REVIEW

**Review by MarkCallow — APPROVED** [review]
The changes to the 2 existing files look fine to me. I haven't looked much at the fmt files.

What is the total size of the `fmt` directory?

**Comment by MarkCallow** [comment]
@VaderY I don't want to hold this and you up until I'm able to release 4.1.0 so please retarget to the ktxtools branch. I attempted to do it on GitHub but it tells me there are conflicts that must be resolved.

**Comment by VaderY** [comment]
Rebased and retargeted
The whole fmt folder is 3.606 MB

**Comment by VaderY** [comment]
@MarkCallow If this is ready to go, could you merge it or should we merge it ourselves?

**Pull request merged**
